<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/07 00:42:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=designer;',
  'username' => 'root',
  'password' => 'Th3s0urc3',
  'name' => 'doctrine',
)),);
