<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/07 00:42:47
sfConfig::add(array(
  'sf_error_404_module' => 'system',
  'sf_error_404_action' => 404,
  'sf_login_module' => 'security',
  'sf_login_action' => 'login',
  'sf_secure_module' => 'security',
  'sf_secure_action' => 'login',
  'sf_module_disabled_module' => 'system',
  'sf_module_disabled_action' => 'disabled',
  'sf_use_database' => true,
  'sf_i18n' => false,
  'sf_compressed' => false,
  'sf_check_lock' => false,
  'sf_csrf_secret' => '523711d471260d89c6df73b819c991b9cbdcc6e5',
  'sf_escaping_strategy' => true,
  'sf_escaping_method' => 'ESC_SPECIALCHARS',
  'sf_no_script_name' => true,
  'sf_cache' => false,
  'sf_etag' => true,
  'sf_web_debug' => false,
  'sf_error_reporting' => 341,
  'sf_file_link_format' => NULL,
  'sf_admin_web_dir' => '/sf/sf_admin',
  'sf_web_debug_web_dir' => '/sf/sf_web_debug',
  'sf_standard_helpers' => array (
  0 => 'Partial',
  1 => 'Cache',
),
  'sf_enabled_modules' => array (
  0 => 'default',
),
  'sf_charset' => 'utf-8',
  'sf_logging_enabled' => false,
  'sf_default_culture' => 'en',
));
