<?php
// auto-generated by sfViewConfigHandler
// date: 2011/03/07 01:12:50
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Stationery Designer', false, false);
  $response->addMeta('description', '', false, false);
  $response->addMeta('keywords', 'stationery designer', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('designer.css', '', array ());
  $response->addStylesheet('jquery-ui.css', '', array ());
  $response->addJavascript('raphael', '', array ());
  $response->addJavascript('uploadify', '', array ());
  $response->addJavascript('farbtastic', '', array ());


