prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

default:
  .actions:
    error_404_module:       system
    error_404_action:       404
 
    login_module:           security
    login_action:           login
 
    secure_module:          security
    secure_action:          login
 
    module_disabled_module: system
    module_disabled_action: disabled

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            523711d471260d89c6df73b819c991b9cbdcc6e5

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
