default:
  http_metas:
    content-type: text/html

  metas:
    title:        Stationery Designer
    description:  
    keywords:     stationery designer
    language:     en
    robots:       index, follow

  stylesheets:    [designer.css, jquery-ui.css]

  javascripts:    [raphael, uploadify, farbtastic]

  has_layout:     true
  layout:         layout
